src/toast.tsx
I get the following error when using this package.
```
Unable to resolve "src/constants" from "node_modules/react-native-reanimated-toasts/lib/commonjs/toast.js"
```
=> fix: import path

src/animations.ts, src/toaster.tsx
=> fix: bottom bars weren't tappable with custom offset

docs/docs/Toaster.md, docs/docs/sonner.md, example/src/App.tsx, src/constants.ts, src/toast.tsx, src/toaster.tsx, src/types.ts, src/use-app-state.ts
=> feat: pause timer when app enters background

docs/docs/Toaster.md, docs/docs/sonner.md, package.json, src/constants.ts, src/tailwind-utils.ts, src/toast.tsx, src/toaster.tsx, src/types.ts, yarn.lock
=> feat: remove cn as dependency and add is as a prop

docs/docs/Toaster.md, docs/docs/sonner.md, example/src/App.tsx, example/src/ToastDemo.tsx, src/toast.tsx
=> feat: custom loading icon

docs/docs/sonner.md, example/src/ToastDemo.tsx, src/animations.ts, src/positioner.tsx, src/toast.tsx, src/toaster.tsx
=> feat: dynamic positioning

src/gestures.tsx
Fixes: https://github.com/gunnartorfis/sonner-native/issues/44
=> fix: warning by gesture handler

example/package.json, package.json, src/gestures.tsx, src/icons.tsx, src/toast.tsx, yarn.lock
=> refactor: remove lucide react native from dependency

example/src/App.tsx, src/constants.ts, src/toaster.tsx, src/types.ts, src/use-colors.ts
Theme was not used when passed to Toaster, closes #68
=> fix: theme was not used when passed to Toaster

src/gestures.tsx
Adds the dependency array of `useAnimatedStyle`
This helps custom bundler for react native web like `vite`.
running examples
=> chore: add dependency array for useAnimatedStyle

example/src/ToastDemo.tsx, src/toast.tsx, src/toaster.tsx, src/types.ts
Infinity was being sent over to the native layer, resulting in a crash.
=> fix: crash when trying to wiggle duration Infinity

docs/docs/Toaster.md, docs/docs/sonner.md, example/src/App.tsx, src/gestures.tsx, src/toaster.tsx, src/types.ts, src/use-colors.ts
- Fixed typo in `swipToDismissDirection` prop to `swipeToDismissDirection`. Updated other related files that uses it. 
- Fixed typo `ivertProps` to `invertProps` in `use-colors.ts` file.
Additional test plan is not needed. Just made typo fixes and it **passes** the current tests.
=> typo fixes for "swipToDismissDirection" and "ivertProps".

example/src/ToastDemo.tsx, src/toast.tsx
Reverts gunnartorfis/sonner-native#89
=> Revert "fix: await the promise to be able to catch its error and a toast"

example/src/ToastDemo.tsx, src/toast.tsx
Reverts gunnartorfis/sonner-native#91
Original PR by @bpingris
=> Revert "Revert "fix: await the promise to be able to catch its error and a toast"" 🙃 

docs/docs/Toaster.md, docs/docs/sonner.md, docs/docs/toast.md, example/src/ToastDemo.tsx, src/constants.ts, src/toast.tsx, src/toaster.tsx, src/types.ts, src/use-colors.ts, src/use-default-styles.ts
Adds rich color support, closes #85 
Added examples to ToastDemo and tested existing ones, light & dark mode.
=> feat: rich colors support

src/gestures.tsx, src/toast.tsx
=> fix: bottom positioned toast should swipe down

README.md, docs/docs/index.md
=> docs: web support 

src/toast.tsx, src/toaster.tsx
Closes #107 
I don't remember why I was applying style and className to the Positioner 🤔
=> fix: toastOption.style wasn't applied

src/toast.tsx
Regression after #97 , closes #111
=> fix: close button press didn't trigger dismiss

src/gestures.tsx
Not sure how this was missed. Related to #44.
N/A
=> fix: add missing worklet directive

CHANGELOG.md, package.json, src/toaster.tsx
=> fix: conditional full window overlay

example/src/ToastDemo.tsx, src/toast.tsx
Fixes: https://github.com/gunnartorfis/sonner-native/issues/151
No special setup required.
Updated the custom JSX component in ToastDemo.tsx of the example app to align components centrally for the "Custom JSX" button.
=> fix: custom jsx component breaks animation

src/toaster.tsx
Not sure if there's a better way of doing this, suggestions appreciated
Closes #174
=> fix: let animation finish before hiding toasts

CHANGELOG.md, example/src/ToastDemo.tsx, package.json, src/toaster.tsx
Simplifies the rendering of differently positioned toasts. 
Closes #194
=> fix: animation for bottom positioned toasts

example/src/ToastDemo.tsx, src/animations.ts, src/positioner.tsx, src/toaster.tsx, src/types.ts
Centered toasts support
Closes #200
=> feat: centered toasts
